#!/usr/bin/env ruby
require 'daemons'

# Current directory
pwd = File.dirname( File.expand_path(__FILE__))
file = pwd + "/bot.rb"

# Set some options
options = {
	:app_name    =>"mitbotd",
	:multiple   => true,
	:mode       => :load,
	:log_output => true,
	:monitor    => true
}

# Run the bot and daemonize it
Daemons.run_proc('mitbotd',options) do
	exec "ruby #{file}"
end
